### ISSUE TITLE
Confusions about getting t1 in prediction. 

### ISSUE THREAD

**Issue by XinL97** [hudson-and-thames/research#100]
In exercise 10.2(d),  the author generates a series of random positive shifted dates to represent t1. From my understanding, I think we only labeled samples with [1, 0, -1] back in chapter 3, then the outputs we get from the model would be a number, can anyone explain how do we associate it with an expiring date (t1) to compute bet concurrents or averages?

**Comment by Harkishan-99** [comment]
@XinL97 As far I can understand you have a problem with understanding concurrency and how it is associated with the vertical barrier (t1), I suggest you read this [blog](https://hudsonthames.org/bagging-in-financial-machine-learning-sequential-bootstrapping-python/), it should help you understand better.

**Comment by PanPip** [comment]
@XinL97 Is this issue solved now?

**Comment by PanPip** [comment]
Closing stale Issue.
