### ISSUE TITLE
Why do you recompute sides before fitting the model?

### ISSUE THREAD

**Issue by robolth** [hudson-and-thames/research#112]
Hi,

In both notebooks where you apply meta-labelling to a primary strategy ([Trend following strategy](https://github.com/hudson-and-thames/research/blob/master/Chapter3/2019-03-06_JJ_Trend-Follow-Question.ipynb) and [Mean reverting strategy](https://github.com/hudson-and-thames/research/blob/master/Chapter3/2019-03-09_AS_BBand-Question.ipynb)), I don't understand why you recompute sides after extracting the meta-labels from the original sides.

In both notebooks, right after adding features and prior to fitting the models, you recompute the sides in the exact same way... as far as I can tell, the columns on which you base  the calculations are unchanged by the added features. So why do you do it? Am I missing something?

Sorry if I missed something obvious here... Thanks for these great notebooks!

**Comment by boyboi86** [comment]
@robolth if my understanding is correct, column 'side' is mainly for primary model to decide to long or short[-1,1]. 

Meta-labels will start to act as secondary layer to to bet or not to bet, hence [0,1].

May need to confirm with others.

**Comment by PanPip** [comment]
@robolth Is this issue solved now?

**Comment by PanPip** [comment]
Closing stale issue.
