### ISSUE TITLE
missing pickle files for Online Portfolio Selection - Momentum

### ISSUE THREAD

**Issue by geofffoster** [hudson-and-thames/research#148]
In the notebook  - Online Portfolio Selection - Momentum - 
https://github.com/hudson-and-thames/research/blob/master/Online%20Portfolio%20Selection/Online%20Portfolio%20Selection%20-%20Momentum.ipynb

I am unable to figure out where to get the following pickle files (or to be able to generate them)
In [5]
nyse_small_eta_optuna
nyse_large_eta_optuna
nyse_small_beta_optuna

any help appreciated

**Comment by akwon31** [comment]
[Attached](https://drive.google.com/open?id=1HVnvK-kB0hpBr9HM0d49BzXq4oa6AwUB) is the link to the files.

**Comment by geofffoster** [comment]
perfect
