### ISSUE TITLE
The requirements.txt file may be out of date

### ISSUE THREAD

**Issue by wolfego** [hudson-and-thames/research#150]
In following the guidance in README.md for windows installation all worked as expected with exception of item 7 on line 60 'pip install -r requirements.txt'.  Perhaps this should have been expected by me but for what it is worth I am sharing.

Attached is a modified requirements file that seems more current for your consideration.
[requirements.txt](https://github.com/hudson-and-thames/research/files/4726191/requirements.txt)

**Comment by PanPip** [comment]
@wolfego Thank you for noticing this! We will update the versions in the `requirements.txt`

**Comment by PanPip** [comment]
Updated `requirements.txt` to match MlFinLab version 0.11.0. Later will need to push them to 0.12.X, but it would require changing some pandas functions in the notebooks and will take some time. Fixed in PR #184.
