### ISSUE TITLE
typos in the formula (NCO)

### ISSUE THREAD

**Issue by Jaden-Jaehoon** [hudson-and-thames/research#154]
[original notebook]
![Screenshot from 2020-06-06 22-05-07](https://user-images.githubusercontent.com/40931326/83945021-b3702300-a842-11ea-8275-3754c0c47117.png)

Lamda should be a diagonal matrix  
![Screenshot from 2020-06-06 22-45-21](https://user-images.githubusercontent.com/40931326/83945696-7f4b3100-a847-11ea-8042-b2e8ad4da110.png)
or
![Screenshot from 2020-06-06 22-46-56](https://user-images.githubusercontent.com/40931326/83945737-ab66b200-a847-11ea-9a97-d68932674ef6.png)

![Screenshot from 2020-06-06 22-41-06](https://user-images.githubusercontent.com/40931326/83945745-b28dc000-a847-11ea-8871-2220f7ad347a.png)

&  The equal sign should be deleted in the formula inverse of C Matrix 
![Screenshot from 2020-06-06 22-41-20](https://user-images.githubusercontent.com/40931326/83945627-eddbbf00-a846-11ea-9c28-039aba9eb900.png)

**Comment by PanPip** [comment]
@Jaden-Jaehoon Thank you for noticing this typo! We will fix it soon.

**Comment by PanPip** [comment]
This typos were fixed in PR #184.
