### ISSUE TITLE
Cross-over

### ISSUE THREAD

**Issue by sydneyquant** [hudson-and-thames/research#19]
Great notebook.

Are you sure you are calculating your moving average cross-over strategy correctly?
Looks like you are not checking for when the averages cross each other, but rather just whether the one is above the other.

**Comment by Jackal08** [comment]
Hi @sydneyquant , 

The typical moving average strategy would say use a 200 and 50 day simple moving average. When the 50 crosses above the 200 then a buy and hold signal is generated. As long as it remains above the 200, the idea is that the trend will persist and thus the buy signal persists. 

Remember that we make use of a CUSUM filter to first reduce the number of events. The number of CUSUM events that coincide with a crossover point are too few for us to then train a meta model. Thus we swapped to a 7 and 15 day sma (very short frames). This was to help the triple barrier method and to let the meta model know what the latest move in trend was. Longer time frames like 50 200 don't work under this framework. 

I may be wrong of course, play around with the meta model, adjust the CUSUM filters, reduce the min_ret argument in the triple barrier method. Maybe there is something we missed. 

Hope this helps
Jacques Joubert
