### ISSUE TITLE
Sample-Data doesn't contain Chapter2 notebook file: 30_minES.csv

### ISSUE THREAD

**Issue by lionelyoung** [hudson-and-thames/research#27]
`Sample-Data` folder doesn't contain Chapter2 data file: `30_minES.csv`

The notebook `2019-03-03_JJ_Sample-Techniques` has this line requiring the data:
`time_bars = pd.read_csv('official_data/30_minES.csv', index_col=0)`

**Comment by Jackal08** [comment]
Re our conversation today on WhatsApp, we need to be careful about the data we provide. Royalties need to be paid to service providers and the exchanges. That's why we don't provide any fixed interval samples or raw tick data. 

We deleted the branch and closed this PR.

**Comment by Jackal08** [comment]
One last note: The research notebooks are done on the full data set but we only provide a small 2 year sample of standard bar types to the community. This allows our research to be sound without violating rules governing the royalties.
