### ISSUE TITLE
Trend following question: primary model prediction

### ISSUE THREAD

**Issue by mpugna** [hudson-and-thames/research#35]
After building your primary model (based on the crossing of two moving averages) you proceed to analyze its metrics. In doing so you state that the predictions of the primary model is always 1 (primary_forecast['pred'] = 1). I don't understand why this is the case. As far as my understanding goes the primary model predictions coincides with the side of the trade. If the fast moving average is above the slow one than the model is predicting to 'go long' as it is expecting an uptrend and hence positive returns. Conversely if the fast average is below the slow one than the model is issuing a 'go shot' signal as it is expecting a downtrend and hence negative returns. If you assume that the primary models predicitons are always 1 aren't you saying that the model is always predicting to go long? Thank you

**Comment by Jackal08** [comment]
Hi @mpugna, 

The section you are referencing to is looking at the performance metrics of the primary model relative to the performance of the meta-model. In this context a 1 represents to take the trade and a 0 to forgo it. 

We are interested in the performance of the primary model, i.e. when is it correct and when it isn't, we do this with the help of the confusion matrix.
