### ISSUE TITLE
Volume 

### ISSUE THREAD

**Issue by gsanc018** [hudson-and-thames/research#51]
When creating bars, your code requires volume to be an integer but for currencies the values need to be in decimals! Tick data for crytocurrencies is widely available so it'll be nice if we could create bars with this package! Thanks!

**Comment by Jackal08** [comment]
Hi @gsanc018 , 

Thank you for the recommendation. I have just made the changes and pushed to the PyPi index. The new version will allow for floating point numbers for volume.

Best regards
Jacques
