### ISSUE TITLE
Missing raw_tick_data.csv in chapter2

### ISSUE THREAD

**Issue by NgHongWai** [hudson-and-thames/research#52]
In research / Chapter2 / Getting Started.ipynb, under the section CSV, in [4], I am not able to locate the file raw_tick_data.csv in ./tutorial_data/raw_tick_data.csv. 
I found only bars.csv files in the folder tutorial data. 
Please advise.

**Comment by Jackal08** [comment]
Hi @NgHongWai,

You have to create the raw_tick_data.csv, see cell 4: 

``` python
# Save to csv
new_data.to_csv('./tutorial_data/raw_tick_data.csv', index=False)
```

The reason for this is that the raw tick data file is rather large, and it is created from the ES_Trades.csv file (which needs to be unziped).

The tutorial_data dir should have 5 files in when you start, if not then please make sure you clone again.

1. ES_Trades.zip
2. dollar_bars.csv
3. tick_bars.csv
4. time_bars.csv
5. volume_bars.csv
