### ISSUE TITLE
Meta-labelling - would be better with a financial example.

### ISSUE THREAD

**Issue by hrpomrx** [hudson-and-thames/research#71]
The meta-labelling example is based on image recognition; it might be better, and much more valuable to have a financial example.

**Comment by Jackal08** [comment]
Hi @hrpomrx, 

There are 5 pieces regarding Meta Labeling that we have provided:
1. The [Toy Example](https://github.com/hudson-and-thames/research/blob/master/Chapter3/2019-03-06_JJ_Meta-Labels-MNIST.ipynb) you reference here, which is on MNIST Data.
2. An example of meta labeling on S&P 500 Emini futures [Trend following strategy](https://github.com/hudson-and-thames/research/blob/master/Chapter3/2019-03-06_JJ_Trend-Follow-Question.ipynb)
3. An example of meta labeling on S&P 500 Emini futures [Mean reverting strategy](https://github.com/hudson-and-thames/research/blob/master/Chapter3/2019-03-09_AS_BBand-Question.ipynb)
4. A full write up and masters project: [Does Meta Labeling Add to Signal Efficacy?](https://github.com/hudson-and-thames/presentations/blob/master/Does%20Meta%20Labeling%20Add%20to%20Signal%20Efficacy.pdf)
5. Slide show presentation on Meta Labeling (S&P500 Emini futures): [Improved Signals](https://github.com/hudson-and-thames/presentations/blob/master/Improved%20Signals.pdf)
