### ISSUE TITLE
Research using cryptocurrency data

### ISSUE THREAD

**Issue by Tardis-Thad** [hudson-and-thames/research#74]
Hi, big fan of your work so far! if you'd like to conduct your research using cryptocurrency markets historical data as well, I'd be happy to provide it for you (for free obviously for research purposes), that includes tick by tick trades, streamed order book data etc. I've also released Python lib recently that should help with integration if you'd be interested.

**Comment by Jackal08** [comment]
Hi @Tardis-Thad, 

Thank you for the kind offer it sounds very interesting. Will email you at: the address provided on your profile.

Tag: @imcu
