### ISSUE TITLE
Question on Trend following notebook. 

### ISSUE THREAD

**Issue by avs20** [hudson-and-thames/research#82]
In the Cell 12 of the Trendfollowing notebook, the raw dataframe looks like this 

![image](https://user-images.githubusercontent.com/9055117/68760791-aab2c800-0638-11ea-8ef5-7909d96d1b5d.png)

Are the `cum_vol`, `cum_dollar` and `cum_ticks` columns the volume, dollar and tick bars. 

Because all other columns present are generated in the notebook but these 3 are not. 

Though these columns are dropped later in the notebook but just wanted to confirm what are these as the volume and dollar values are almost same but the tick value differs. 

Thanks

**Comment by Jackal08** [comment]
Hi @avs20,

The cum vol, dollar, tick columns are to show the accumulation of volume, dollars, and ticks, that took place in that bucket. 

In that data set (dollar bars) you can see that the dollars traded are pretty fixed around 70'000'000 USD.

So to confirm: that data set is dollar bars data but the 3 columns just show the accumulation of the respective fields.
