### ISSUE TITLE
get_daily_vol problem with uniqueness of index

### ISSUE THREAD

**Issue by gsanc018** [hudson-and-thames/research#84]
When ticks are only index to the second, for example '2019-07-17 03:34:23', we might get multiple bars index by the same index (for example, I have 6 dollar bars with that index above). The cum_buy_vol is 0 for all but the first with that index.
(We could just increase the threshold I guess...)

This creates a broadcasting problem when trying to use the get_daily_vol. The dataset you guys used was up to nanoseconds so it was very unlikely that you to get this issue.

I tried
data = data.loc[~data.index.duplicated(keep='first')]
but I think we end up losing information with this.

Perhaps you can add,
    try:
        daily_vol = (close_prices.loc[daily_vol.index] / 
            close_prices.loc[pd.to_datetime(daily_vol.values, utc=True)].values-1) # daily returns
    except Exception as e:
        print('error: {}\nplease confirm no duplicate indices'.format(type(e).__name__, e))

**Comment by gsanc018** [comment]
Found a solution that artificially adds nanoseconds to duplicated indicies making them unique.
https://stackoverflow.com/questions/43297853/modifying-timestamps-in-pandas-to-make-index-unique


```
data.index = data['date_time']
values = BTC.index.duplicated(keep='first').astype(float)
values[values==0] = np.NaN
missings = np.isnan(values)
cumsum = np.cumsum(~missings)
diff = np.diff(np.concatenate(([0.], cumsum[missings])))
values[missings] = -diff
result = data.index + np.cumsum(values).astype(np.timedelta64)
data['timestamp'] = result
data.index = result
```

**Comment by Jackal08** [comment]
Hi @gsanc018, 

I see that @proskurin has addressed this bug fix in a package update to mlfinlab. 

Please do let us know if the problem persists.
