### ISSUE TITLE
Is triple-labeling and meta-labeling a labeling?

### ISSUE THREAD

**Issue by MislavSag** [hudson-and-thames/research#90]
I have read chapter 3 in the book, Labeling section in your documentation and the jupyter notebook in this repo, but I am still confused about the logic of how triple-barrier and meta labeling works.

If I understand it right, you use CUSUM filter method to identify events from which barrier will start? When the cumulative sum of returns is grater then expected value, in some short period, the event is triggered. My question is: why do you use CUSUM filter to identify events? Are there some other possibilities?

If I get it right CUSUM tells us when we enter the position (long or short) but isn't the purpose of ML model to tell us that? 

This approach confuses me because I thought of labeling (in classification setting) as 1, 0 (or 1, 0, -1) labeling of the target. In triple-labeling we already assume trading time by CUSUM filer, and then only decide trade or not. It seems to me this is not really a labeling technique in the usual sense. It makes labeling after we decide when we will enter the position but isn't the purpose of labeling to allow us to train the model the which will tell us when to enter the position in the first place?

**Comment by Despair2000** [comment]
The CUSUM filters purpose is to avoid getting whipsawed when price is hovering near a barrier.

**Comment by MislavSag** [comment]
Can you please be more specific? Why use cusum filter events for the time when enter position and not some ml algorithm?

**Comment by Jackal08** [comment]
@MislavSag The idea in the textbook is not to label every single day or observation as an up or down move. The idea is that markets follow random walks and when new information enters the system we see prices drift towards the new price equilibrium, in a random walk fashion. 

That means that we want to build models that trade specific events / market annomalies, not every day. The CUSUM filters is used as an example of trading structural break. It is a filter that allows us to focus only on this type of event and to trade it. You are correct in saying that in the example the CUSUM filter trigers a trade event. 

Once an event is triggered you will need another rule/model to determine the side of the position. This could be a technical trading strategy or an ML model and so on. If however, you don't provide the side argument to the triple barrier events function, you are then saying that I want to label the data using the triple barrier labeling. This labeled data is used to train an ML model to predict side. 

If you provide the side then the function will return the meta labels.

**Comment by MislavSag** [comment]
OK, I think it's clear now. We can say there are 2 approaches:
1. Use traditional labeling (price change grater/lower than some threshold).
2. Use the triple-barrier method. There are 2 possibilities:
a) use sign from trade strategy (like SMA crossing) or use sign from step 1. Events can be calculated from CUSUM filter or some other structural brake indicators (from chapter 17)
b) don't use signs. Form labels and then apply step 1. Use triple barrier method (optional). Use 1, 0 labels from step 2. and train binary classification.

Did I get it right?

**Comment by Jackal08** [comment]
Hmm thats a bit tricky for me to follow. 

The following may be more clear:
1. If you provide a side of the trade then it applies meta labeling.
2. If you don't provide a side then it applies Triple Barrier labeling.

* You can determine the side by using something like a moving average cross over.
* We use filters to trade specific events rather than labeling every day
