### ISSUE TITLE
Doubt regarding the price used to form labels ?

### ISSUE THREAD

**Issue by Harkishan-99** [hudson-and-thames/research#92]
As I saw the research [notebook](https://github.com/hudson-and-thames/research/blob/master/Chapter3/2019-03-03_AS_JJ_Chapter3-Part1.ipynb) for creating the labels, I found it very absurd that you all have used the closing price of the sample bars (i.e. dollar bars in the notebook) for generating the labels ( highlighted in the image below). 
![labeling_research](https://user-images.githubusercontent.com/45006182/74944993-fab1df80-541c-11ea-91f7-47f97cd5a13d.PNG)

As the triple_barrier_events and the get_bin function is a path-dependent function so by taking the closing price of the bars we are ignoring the original price path. I would like to demonstrate the problem in below image. The blue graph represents the tick price, the red crosses represent the sample dollar bars. Let's consider the bar sample at point A and B( purple in the image) and the time difference between the bar is 1 hour. If we had considered the label for the bar at A using the closing price only for a vertical barrier of 1 hour then we would have either got a label as 1 (buy) or 0 (do nothing). But actually the price had gone down 0.5% which would have been labelled as -1(sell) if we had used the tick price as raw_price to generate the path for the labels.

![dollar_value_sampled_bar](https://user-images.githubusercontent.com/45006182/74946012-aa3b8180-541e-11ea-80ed-ef69b21319d0.png)

**Comment by Jackal08** [comment]
That's a very good point. I think it makes sense. We should be measuring the take profit and stop with respect to the tick prices and not the close of the dollar bars. 

In the setting we have chosen where we use the close of the dollar bars, we could use it as a heuristic for performance, though your method is certainly more correct. I would welcome a PR to fix this notebook.

Thanks for the great work.

**Comment by robolth** [comment]
Hi, if I understood correctly, that means we should use the low price of the bar to decide if it crossed the stop loss barrier, and the high one to decide if it crosses the profit taking barrier. It does make sense, however Lopez de Prado uses the close prices in his book...
