### ISSUE TITLE
May i ask the relationship between "ticker" and "nearest_contract" in chapter 2 Futures_Roll_Trick.ipynb??

### ISSUE THREAD

**Issue by marcusau** [hudson-and-thames/research#97]
I understand the meaning of "Ticker" , however, can i ask when there will be a difference between  "ticker" and "nearest_contract" ??

I have my own dataset for non-US future market. 

Thanks a lot

**Comment by proskurin** [comment]
Your data set may contain several futures contracts. Ticker column refers to contract name, while nearest_contract is the ticker of the nearest contract. For example, you have monthly futures data from March till December with tickers 'Mar', 'Apr', May', .....
Right now the nearest contract is March. So your data set will be:
date open high low close volume ticker nearest contract
03.01 22 22 22 22 1000 Mar Mar
03.01 25 27 29 30 150 Apr Mar

**Comment by marcusau** [comment]
Thanks for your prompt response.

So your dataset contains all OHLC of different contract in "single" columns.  based on your example above:

date open high low close volume ticker nearest contract
03.01 22 22 22 22 1000 Mar Mar
03.01 25 27 29 30 150 Apr Mar

The OHLC of March, April are stored in the same columns, right?

**Comment by proskurin** [comment]
Yes, you are right

**Comment by marcusau** [comment]
got it .

So if i have OHLC data of future contract in different months, i should concatenate them into single df before performing future-rolling trick, right?

**Comment by proskurin** [comment]
Yes
